# Generated by Django 5.1 on 2025-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_images_delete_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='description',
        ),
        migrations.AddField(
            model_name='product_images',
            name='product_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
