# Generated by Django 5.1 on 2025-02-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_images_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Images',
            new_name='Product_Listings',
        ),
        migrations.AlterModelOptions(
            name='product_listings',
            options={'verbose_name_plural': 'Product_Listings'},
        ),
    ]
