# Generated by Django 5.1 on 2025-02-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_images_product_listings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listings',
            name='product_image',
            field=models.ImageField(default=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product_listings',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product_listings',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_listings',
            name='product_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
