# Generated by Django 5.1 on 2025-02-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_listings_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_listings',
            name='product_image',
            field=models.ImageField(default=True, null=True, upload_to='productlistings/'),
        ),
    ]
