# Generated by Django 4.2.11 on 2024-12-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
