# Generated by Django 5.1 on 2024-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_featured_products_delete_featuredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image', models.ImageField(upload_to='brands')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
