# Generated by Django 5.2 on 2025-05-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contact_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
